// frontend/components/landing/Features.vue
<template>
  <section class="py-24 bg-gray-50 relative">
    <div class="absolute inset-0 bg-gradient-to-b from-white to-transparent"></div>
    <div class="container mx-auto px-6 relative">
      <div class="text-center max-w-3xl mx-auto mb-20">
        <h2 class="text-3xl md:text-4xl font-bold mb-6 text-gray-900">
          Outshine your competition with your own mobile app.
        </h2>
        <p class="text-lg text-gray-600">Transform your practice with powerful features designed for growth.</p>
      </div>
      
      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
        <!-- Mobile Rewards -->
        <div class="flex flex-col items-center text-center bg-orange-50 p-8 rounded-2xl shadow-lg hover:shadow-xl transition-all duration-300 transform hover:-translate-y-1">
          <div class="w-16 h-16 mb-6">
            <div class="bg-gradient-to-br from-[#20B2AA] to-[#008B8B] rounded-xl p-4">
              <svg xmlns="http://www.w3.org/2000/svg" class="w-8 h-8 text-white" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"></polygon>
              </svg>
            </div>
          </div>
          <h3 class="text-xl font-semibold mb-4 text-gray-900">Mobile Rewards</h3>
          <p class="text-gray-600 leading-relaxed">Engage patients with a rewards program that drives repeat visits and increases revenue.</p>
        </div>

        <!-- Memberships -->
        <div class="flex flex-col items-center text-center bg-orange-50 p-8 rounded-2xl shadow-lg hover:shadow-xl transition-all duration-300 transform hover:-translate-y-1">
          <div class="w-16 h-16 mb-6">
            <div class="bg-gradient-to-br from-[#20B2AA] to-[#008B8B] rounded-xl p-4">
              <svg xmlns="http://www.w3.org/2000/svg" class="w-8 h-8 text-white" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <rect x="1" y="4" width="22" height="16" rx="2" ry="2"></rect>
                <line x1="1" y1="10" x2="23" y2="10"></line>
              </svg>
            </div>
          </div>
          <h3 class="text-xl font-semibold mb-4 text-gray-900">Memberships</h3>
          <p class="text-gray-600 leading-relaxed">Create and manage membership programs that generate predictable recurring revenue.</p>
        </div>

        <!-- Patient Financing -->
        <div class="flex flex-col items-center text-center bg-orange-50 p-8 rounded-2xl shadow-lg hover:shadow-xl transition-all duration-300 transform hover:-translate-y-1">
          <div class="w-16 h-16 mb-6">
            <div class="bg-gradient-to-br from-[#20B2AA] to-[#008B8B] rounded-xl p-4">
              <svg xmlns="http://www.w3.org/2000/svg" class="w-8 h-8 text-white" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <line x1="12" y1="1" x2="12" y2="23"></line>
                <path d="M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6"></path>
              </svg>
            </div>
          </div>
          <h3 class="text-xl font-semibold mb-4 text-gray-900">Patient Financing</h3>
          <p class="text-gray-600 leading-relaxed">Offer flexible payment options to make treatments more accessible to patients.</p>
        </div>

        <!-- Ecommerce -->
        <div class="flex flex-col items-center text-center bg-orange-50 p-8 rounded-2xl shadow-lg hover:shadow-xl transition-all duration-300 transform hover:-translate-y-1">
          <div class="w-16 h-16 mb-6">
            <div class="bg-gradient-to-br from-[#20B2AA] to-[#008B8B] rounded-xl p-4">
              <svg xmlns="http://www.w3.org/2000/svg" class="w-8 h-8 text-white" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <circle cx="9" cy="21" r="1"></circle>
                <circle cx="20" cy="21" r="1"></circle>
                <path d="M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6"></path>
              </svg>
            </div>
          </div>
          <h3 class="text-xl font-semibold mb-4 text-gray-900">Ecommerce</h3>
          <p class="text-gray-600 leading-relaxed">Sell products and services directly through your branded mobile app.</p>
        </div>

        <!-- Patient Engagement -->
        <div class="flex flex-col items-center text-center bg-orange-50 p-8 rounded-2xl shadow-lg hover:shadow-xl transition-all duration-300 transform hover:-translate-y-1">
          <div class="w-16 h-16 mb-6">
            <div class="bg-gradient-to-br from-[#20B2AA] to-[#008B8B] rounded-xl p-4">
              <svg xmlns="http://www.w3.org/2000/svg" class="w-8 h-8 text-white" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"></path>
              </svg>
            </div>
          </div>
          <h3 class="text-xl font-semibold mb-4 text-gray-900">Patient Engagement</h3>
          <p class="text-gray-600 leading-relaxed">Keep patients connected with messaging, notifications, and appointment reminders.</p>
        </div>

        <!-- Business Intelligence -->
        <div class="flex flex-col items-center text-center bg-orange-50 p-8 rounded-2xl shadow-lg hover:shadow-xl transition-all duration-300 transform hover:-translate-y-1">
          <div class="w-16 h-16 mb-6">
            <div class="bg-gradient-to-br from-[#20B2AA] to-[#008B8B] rounded-xl p-4">
              <svg xmlns="http://www.w3.org/2000/svg" class="w-8 h-8 text-white" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <line x1="18" y1="20" x2="18" y2="10"></line>
                <line x1="12" y1="20" x2="12" y2="4"></line>
                <line x1="6" y1="20" x2="6" y2="14"></line>
              </svg>
            </div>
          </div>
          <h3 class="text-xl font-semibold mb-4 text-gray-900">Business Intelligence</h3>
          <p class="text-gray-600 leading-relaxed">Get insights into patient behavior and business performance with detailed analytics.</p>
        </div>
      </div>
    </div>
  </section>
</template>

// frontend/components/landing/Features.tsx
"use client";

import React from 'react';

interface FeatureCardProps {
  icon: React.JSX.Element;
  title: string;
  description: string;
}

const FeatureCard = ({ icon, title, description }: FeatureCardProps) => (
  <div className="flex flex-col items-center text-center bg-orange-50 p-8 rounded-2xl shadow-lg hover:shadow-xl transition-all duration-300 transform hover:-translate-y-1">
    <div className="w-16 h-16 mb-6">
      <div className="bg-gradient-to-br from-[#20B2AA] to-[#008B8B] rounded-xl p-4">
        {icon}
      </div>
    </div>
    <h3 className="text-xl font-semibold mb-4 text-gray-900">{title}</h3>
    <p className="text-gray-600 leading-relaxed">{description}</p>
  </div>
);

const Features = () => {
  const features = [
    {
      title: "Mobile Rewards",
      description: "Engage patients with a rewards program that drives repeat visits and increases revenue.",
      icon: (
        <svg xmlns="http://www.w3.org/2000/svg" className="w-8 h-8 text-white" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
          <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"></polygon>
        </svg>
      )
    },
    {
      title: "Memberships",
      description: "Create and manage membership programs that generate predictable recurring revenue.",
      icon: (
        <svg xmlns="http://www.w3.org/2000/svg" className="w-8 h-8 text-white" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
          <rect x="1" y="4" width="22" height="16" rx="2" ry="2"></rect>
          <line x1="1" y1="10" x2="23" y2="10"></line>
        </svg>
      )
    },
    {
      title: "Patient Financing",
      description: "Offer flexible payment options to make treatments more accessible to patients.",
      icon: (
        <svg xmlns="http://www.w3.org/2000/svg" className="w-8 h-8 text-white" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
          <line x1="12" y1="1" x2="12" y2="23"></line>
          <path d="M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6"></path>
        </svg>
      )
    },
    {
      title: "Ecommerce",
      description: "Sell products and services directly through your branded mobile app.",
      icon: (
        <svg xmlns="http://www.w3.org/2000/svg" className="w-8 h-8 text-white" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
          <circle cx="9" cy="21" r="1"></circle>
          <circle cx="20" cy="21" r="1"></circle>
          <path d="M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6"></path>
        </svg>
      )
    },
    {
      title: "Patient Engagement",
      description: "Keep patients connected with messaging, notifications, and appointment reminders.",
      icon: (
        <svg xmlns="http://www.w3.org/2000/svg" className="w-8 h-8 text-white" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
          <path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"></path>
        </svg>
      )
    },
    {
      title: "Business Intelligence",
      description: "Get insights into patient behavior and business performance with detailed analytics.",
      icon: (
        <svg xmlns="http://www.w3.org/2000/svg" className="w-8 h-8 text-white" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
          <line x1="18" y1="20" x2="18" y2="10"></line>
          <line x1="12" y1="20" x2="12" y2="4"></line>
          <line x1="6" y1="20" x2="6" y2="14"></line>
        </svg>
      )
    }
  ];

  return (
    <section className="py-24 bg-gray-50 relative">
      <div className="absolute inset-0 bg-gradient-to-b from-white to-transparent"></div>
      <div className="container mx-auto px-6 relative">
        <div className="text-center max-w-3xl mx-auto mb-20">
          <h2 className="text-3xl md:text-4xl font-bold mb-6 text-gray-900">
            Outshine your competition with your own mobile app.
          </h2>
          <p className="text-lg text-gray-600">Transform your practice with powerful features designed for growth.</p>
        </div>
        
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {features.map((feature) => (
            <FeatureCard
              key={feature.title}
              icon={feature.icon}
              title={feature.title}
              description={feature.description}
            />
          ))}
        </div>
      </div>
    </section>
  );
};

export default Features;
